---
- name: Deploy Calculator App with Docker
  hosts: webserver
  become: true

  tasks:

    - name: Pull latest Docker image
      command: docker pull dknights/scientific-calculator

    - name: Stop and remove existing container if running
      command: docker rm -f scientific-calculator
      ignore_errors: yes

    - name: Run new container
      command: docker run -dit --name scientific-calculator dknights/scientific-calculator