---
- name: Pull Docker Image from Docker Hub
  hosts: localhost
  remote_user: diksha
  become: false
  tasks:
    - name: Pull Docker Image
      docker_image:
        name: "dknights/calculator"
        source: pull
      register: docker_pull_result

    - name: Display Docker Pull Result
      debug:
        var: docker_pull_result
        
    - name: Start Docker service
      service:
        name: docker
        state: started
        
    - name: stop container
      shell: docker stop calculator
      ignore_errors: yes  
      
    - name: rm container
      shell: docker rm calculator
      ignore_errors: yes
     
    - name: Running container
      shell: docker run -it -d --name calculator dknights/calculator /bin/bash


